apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-collector-deployment
  labels:
    app: micro-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-collector
  template:
    metadata:
      labels:
        app: micro-collector
    spec:
      containers:
        - name: micro-collector
          image: mp/micro-collector
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: EUREKA_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-configmap
                  key: eureka_address
            - name: PREFER_IP_ADDRESS
              value: 'true'
---
apiVersion: v1
kind: Service
metadata:
  name: micro-collector-service
spec:
  selector:
    app: micro-collector
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: micro-collector-external-service
spec:
  selector:
    app: micro-collector
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 32082