apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-recipient-deployment
  labels:
    app: micro-recipient
spec:
  replicas: 2
  selector:
    matchLabels:
      app: micro-recipient
  template:
    metadata:
      labels:
        app: micro-recipient
    spec:
      containers:
        - name: micro-recipient
          image: mp/micro-recipient
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: RABBIT_PORT
              valueFrom:
                configMapKeyRef:
                  name: rabbit-configmap
                  key: rabbit_port
            - name: RABBIT_HOST
              valueFrom:
                configMapKeyRef:
                  name: rabbit-configmap
                  key: rabbit_host
            - name: RABBIT_EXCHANGE_NAME
              valueFrom:
                configMapKeyRef:
                  name: rabbit-configmap
                  key: exchange_name
            - name: RABBIT_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: rabbit-configmap
                  key: queue_name
            - name: RABBIT_ROUTING_KEY
              valueFrom:
                configMapKeyRef:
                  name: rabbit-configmap
                  key: routing_key_name
            - name: EUREKA_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-configmap
                  key: eureka_address
            - name: PREFER_IP_ADDRESS
              value: 'true'
---
apiVersion: v1
kind: Service
metadata:
  name: micro-recipient-service
spec:
  selector:
    app: micro-recipient
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: micro-recipient-external-service
spec:
  selector:
    app: micro-recipient
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 32081