apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
data:
  prometheus.rules: |-
    groups:
    - name: Instance Is Down
      rules:
        - alert: InstanceDown
          expr: up{job="microservices"} < 1
          for: 5m
  prometheus.yml: |-
    global:
      scrape_interval: 30s
      scrape_timeout: 10s

    rule_files:
      - alert.yml

    scrape_configs:
      - job_name: microservices
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - 'micro-sender-service:8080'
              - 'micro-recipient-service:8081'
              - 'micro-collector-service:8082'
              - 'micro-visualizer-service:8083'
      - job_name: 'kubernetes-service-endpoints'
        metrics_path: /actuator/prometheus
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_name