apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-deployment
  labels:
    app: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
        - name: rabbit
          image: rabbitmq:3-management
          ports:
          - containerPort: 5672
          - containerPort: 15672
          env:
            - name: RABBIT_  
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-service
spec:
  selector:
    app: rabbit
  ports:
    - name: queue
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-management-service
spec:
  selector:
    app: rabbit
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 32672